---
parent: 'test_cases/test_branch_openshift_ansible_logging_json_file.yml'
overrides:
  sync_repos:
    - name: "openshift-ansible"
    - name: "origin-aggregated-logging"
      type: "pull_request"